version: '3'
services:
  antikythera:
    hostname: antikythera-k8s.local
    build:
      context: docker/
    environment:
      - ANTIKYTHERA_INSTANCE_DEP=${ANTIKYTHERA_INSTANCE_DEP}
    volumes:
      - ./:/app
    ports:
      - 8080:8080
